version: '3'

services:
  app:
    build: .
    container_name: prisma-api
    entrypoint: .docker/entrypoint.sh
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    depends_on:
      - db
    extra_hosts:
      - 'host.docker.internal:172.17.0.1'
    networks:
      - prisma-network

  db:
    image: postgres:15.2
    container_name: prisma-db
    restart: always
    tty: true
    volumes:
      - data_postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    networks:
      - prisma-network

networks:
  prisma-network:
    driver: bridge

volumes:
  data_postgres: {}

